#!/bin/bash
# $Date 05/03/2024

#varaibales
BASE= /Users/Abhishek/script2
DAYS=10
DEPTH=1
RUN=0
# check if directory is present or not

if [ ! -d $BASE ]
then 
    echo "directory does not exits: $BASE"
    exit 1
fi

# create archive folder if not present

if [ ! -d $BASE/archive ]
then
     mkdir $BASE/archive
fi

# find the list of files larger than 20MB

for i in 'find $BASE -maxdepth $DEPTH -type f -size +20M'
do 
   if [ $RUN -eq 0 ]
    then
      gzip $i || exit 1
      mv $i.gz $BASE/archive || exit 1
   fi  
done
